caseArcContIntro <- "The judge determines release status  for individuals whose cases are not disposed of at arraignment. Charged individuals may 1) be released on their own recognizance  (\"ROR\") with the requirement that they return to court at a future date, 2) be released with conditions such as enrollment in Supervised Release, 3) have monetary bail set on their case, or 4) be remanded into custody. The judge must set the least restrictive conditions necessary that will reasonably assure an individual's return to court.<br/><br/>
Bail may be set on cases with a \"Qualifying Offense.\" Most Qualifying Offenses are violent felonies, such as robbery, assault, certain criminal contempt charges, misdemeanor and felony sex offenses, and homicide. Not all Qualifying Offenses will result in bail, however. Judges may still choose ROR, Supervised Release, or, in select cases, remand. In rare instances, such as the individual being charged repeatedly and willfully failing to appear in court, or committing harm to person or property while released on another crime involving harm to a person or property, a judge may set bail even if the charged offense is not a Qualifying Offense. If an individual's bail is not posted, the New York City Department of Correction detains them in jail until the next court date.<br/><br/>
In 2019, 14% of misdemeanor cases and 48.2% of felony cases had bail set. The graphs below provide information about cases that survived arraignment, broken down by top charge category, offense, release status, and bail amount."

bailSummCap <- "The graph below shows the total number of cases where bail was requested by an Assistant D.A. and the total number of cases where bail was set by the judge. This graph excludes cases with dollar bail set."

bailReqSetCap <- "The graph below illustrates whether bail was requested by an Assistant D.A. and whether bail was subsequently set by the judge. This graph excludes cases with dollar bail set."

medBailCap <- "The graph below shows the median bail requested by an Assistant D.A. and the median bail set by a judge for each charge category. The charge category is based on the top offense at arraignment. This graph excludes cases with dollar bail set."

dollarBailCap <- "The bail graphs all exclude cases with dollar bail set. The count below shows the number of cases where this is the case."