version: "3.7"

services:
  shiny:
    build: app
    user: 'shiny'
    volumes:
      - /var/cache/renv:/renv
      - shiny_logs:/var/log/shiny-server
    env_file: .env

volumes:
  shiny_logs:
